/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panin.application.form.productos;

import com.panin.application.form.other.Card;
import com.panin.application.form.other.Model_Card;

/**
 *
 * @author USUARIO
 */
public class FormAgregarNuevoProducto extends javax.swing.JPanel {

    /**
     * Creates new form FormMostrarProductos
     */
    public FormAgregarNuevoProducto() {
        initComponents();
//        searchHeader21.setBackground(getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

//        searchHeader21 = new com.panin.application.utilities.SearchHeader2();
        panelCrearNuevoProducto = new com.panin.application.form.productos.PanelNuevoProducto();
//        this.add(new Card(new Model_Card(new javax.swing.ImageIcon(getClass().getResource("/imagenes/utilidad/agregar.png")), "", "", "Descripcion"), getBackground(), formClass));
//	    String formClass = "PanelIngresarProducto";


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
//                .addComponent(searchHeader21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent( panelCrearNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
//                .addComponent(searchHeader21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent( panelCrearNuevoProducto , javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private com.panin.application.form.productos.FormVistaProductos formVistaProductos1;
  private com.panin.application.form.productos.PanelNuevoProducto panelCrearNuevoProducto;

//    private com.panin.application.utilities.SearchHeader2 searchHeader21;
    // End of variables declaration//GEN-END:variables
}
