/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panin.application.form.productos;

import com.panin.application.form.other.*;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author ricke
 */
public class MainFormProductos extends javax.swing.JPanel {

    /**
     * Creates new form FormIngresarI
     */
    public MainFormProductos() {
        
        initComponents();
        searchHeader21.setBackground(getBackground());
   
//		lb.putClientProperty(FlatClientProperties.STYLE, "" + "font:$h1.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHeader21 = new com.panin.application.utilities.SearchHeader2();
        formMostrarProductos = new com.panin.application.form.productos.FormMostrarProductos();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formMostrarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchHeader21, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(searchHeader21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formMostrarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify                     
	private javax.swing.JLabel lb;
	private com.panin.application.utilities.SearchHeader sheader;
	// End of variables declaration                   

    // Variables declaration - do not modify                     
    private com.panin.application.form.productos.FormMostrarProductos formMostrarProductos;
    private com.panin.application.utilities.SearchHeader2 searchHeader21;
    // End of variables declaration               
}
