/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panin.application.form.productos;

import com.formdev.flatlaf.FlatClientProperties;
import com.panin.controladores.ControladorComprasInsumos;
import com.panin.controladores.ControladorComprasProductos;
import com.panin.controladores.ControladorConversion;
import com.panin.controladores.ControladorUnidadMedida;
import com.panin.entidades.ComprasInsumo;
import com.panin.entidades.ComprasProducto;
import com.panin.entidades.Conversion;
import com.panin.entidades.Producto;
import com.panin.entidades.UnidadMedida;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author USUARIO
 */
public class panelRegistrosCompraProducto extends javax.swing.JPanel {

    private DefaultTableModel modelTable;

    /**
     * Creates new form panelRegistrosCompraProducto
     */
    public panelRegistrosCompraProducto() {
        String[] columnas = new String[]{
            "Id", "Fecha", "Hora", "Marca", "Cantidad", "Unidad Medida", "Precio"
        };
        modelTable = new DefaultTableModel(columnas, 0);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jComboxUnidades = new javax.swing.JComboBox<>();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Cantidad", "Unidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Desde:");

        jLabel3.setText("Hasta:");

        jDateHasta.setMinimumSize(new java.awt.Dimension(85, 22));

        jComboxUnidades.setMinimumSize(new java.awt.Dimension(85, 22));
        jComboxUnidades.setPreferredSize(new java.awt.Dimension(85, 22));
        jComboxUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboxUnidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jComboxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboxUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboxUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboxUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboxUnidadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<UnidadMedida> jComboxUnidades;
    private com.toedter.calendar.JDateChooser jDateDesde;
    private com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private List<ComprasProducto> listaComprasProductos;
    private Producto producto;

    void iniciar(Producto producto) {
        this.producto = producto;
        ControladorComprasProductos controladorCompraProducto = new ControladorComprasProductos();
        this.listaComprasProductos = controladorCompraProducto.obtenerComprasdeUnProducto(producto);
        this.listaComprasProductos.sort(Collections.reverseOrder());
        table.setEnabled(false);

        // Crear un renderizador para centrar el contenido
        DefaultTableCellRenderer rendererCentrado = new DefaultTableCellRenderer();
        rendererCentrado.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer rendererDerecha = new DefaultTableCellRenderer();
        rendererDerecha.setHorizontalAlignment(SwingConstants.RIGHT);

        // Para alinear a la derecha o centrar
        table.getColumnModel().getColumn(0).setCellRenderer(rendererCentrado);
        table.getColumnModel().getColumn(1).setCellRenderer(rendererCentrado);
        table.getColumnModel().getColumn(2).setCellRenderer(rendererCentrado);
        table.getColumnModel().getColumn(4).setCellRenderer(rendererCentrado);
        table.getColumnModel().getColumn(3).setCellRenderer(rendererDerecha);
        table.getColumnModel().getColumn(5).setCellRenderer(rendererDerecha);
//        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Aplicar el renderizador a todas las columnas (puedes especificarlo por columna)
        for (UnidadMedida item : producto.getIdTipoMedida().getUnidadMedidaCollection()) {
            jComboxUnidades.addItem(item);
        }

        actualizarLista();
        actualizarUnidadMedida();
        busquedaPorFecha();

    }

    public List<ComprasProducto> getListaCompraProducto() {
        return listaComprasProductos;
    }

    public void setListaInsumos(List<ComprasProducto> listaComprasProductos) {
        this.listaComprasProductos = listaComprasProductos;
        this.listaComprasProductos.sort(Collections.reverseOrder());

    }

    private void actualizarLista() {

        UnidadMedida medidaSeleccionada = (UnidadMedida) jComboxUnidades.getSelectedItem();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");

        SimpleDateFormat formatterh = new SimpleDateFormat("HH:mm:ss:");
        String hora;

        for (ComprasProducto fila : listaComprasProductos) {
            String marca = "NA";
            DecimalFormat df = new DecimalFormat("#,##0.00");
            ControladorUnidadMedida controladorUnidadMedida = new ControladorUnidadMedida();
            ControladorConversion controladorConversion = new ControladorConversion();
            BigDecimal precioCalculado = fila.getPrecio();
            BigDecimal cantidadCalculada = fila.getCantidad();
            String unidadAbreviatura = fila.getUnidadMedida().toString();
            hora = fila.getHora().toString();
            if (fila.getUnidadMedida().isUnidadBase()) {
                precioCalculado = precioCalculado.multiply(fila.getCantidad());
            } else {
                UnidadMedida umb = controladorUnidadMedida.obtenerUnidadBase(fila.getUnidadMedida());
                Conversion conversion = controladorConversion.obtenerFactorConversion(umb, fila.getUnidadMedida());
                cantidadCalculada = fila.getCantidad().multiply(conversion.getFactorConversion());
                precioCalculado = precioCalculado.multiply(cantidadCalculada);
            }
//            System.out.println(medidaSeleccionada.isUnidadBase());
            if (!medidaSeleccionada.isUnidadBase()) {
                cantidadCalculada = cantidadCalculada.multiply(controladorConversion.obtenerFactorConversion(controladorUnidadMedida.obtenerUnidadBase(medidaSeleccionada), medidaSeleccionada).getFactorConversion());
                unidadAbreviatura = medidaSeleccionada.toString();
//                System.out.println("Medida seleccionada " + unidadAbreviatura);
            }

            if (fila.getMarcaInsumo() != null) {
                marca = fila.getMarcaInsumo().getNombre();
            }

            String strDate = formatter.format(fila.getFecha());
            String strHora = formatter.format(fila.getHora());
            BigDecimal redondeado = precioCalculado.setScale(1, RoundingMode.HALF_UP);
            double valorDouble = redondeado.doubleValue();
            String cantidadFormat = df.format(cantidadCalculada.doubleValue());
            String precioFormat = df.format(valorDouble);
            modelTable.addRow(new Object[]{fila.getId().toString(), strDate, hora, marca, cantidadFormat, unidadAbreviatura, precioFormat});
        }

    }

    private void actualizarUnidadMedida() {
        jComboxUnidades.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                System.out.println("Cambio de medida");
                modelTable.setRowCount(0);
                actualizarLista();
            }
        });
    }

    private void busquedaPorFecha() {

        jDateDesde.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {

                if ("date".equals(e.getPropertyName())) {
                    jDateHasta.setMinSelectableDate(jDateDesde.getDate());
                    ControladorComprasProductos controladorComprasProductos = new ControladorComprasProductos();
                    if (jDateHasta.getDate() == null) {
                        listaComprasProductos = controladorComprasProductos.obtenerComprasDesdeProducto(producto, jDateDesde.getDate());
                    } else {
                        listaComprasProductos = controladorComprasProductos.obtenerComprasDesdeHastaProducto(producto, jDateDesde.getDate(), jDateHasta.getDate());
                    }
                    listaComprasProductos.sort(Collections.reverseOrder());
                    modelTable.setRowCount(0);
                    actualizarLista();
                }

            }
        });
        jDateHasta.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {

                if ("date".equals(e.getPropertyName())) {
                    jDateDesde.setMaxSelectableDate(jDateHasta.getDate());
                    ControladorComprasProductos controladorComprasProductos = new ControladorComprasProductos();
                    if (jDateDesde.getDate() == null) {
                        listaComprasProductos = controladorComprasProductos.obtenerComprasHastaProducto(producto, jDateHasta.getDate());
                    } else {
                        listaComprasProductos = controladorComprasProductos.obtenerComprasDesdeHastaProducto(producto, jDateDesde.getDate(), jDateHasta.getDate());
                    }
                    listaComprasProductos.sort(Collections.reverseOrder());
                    modelTable.setRowCount(0);
                    actualizarLista();
                }

            }
        });

    }

    public void agregarCompra(ComprasProducto nuevaCompra) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");

        SimpleDateFormat formatterh = new SimpleDateFormat("HH:mm:ss:");
        ControladorUnidadMedida controladorUnidadMedida = new ControladorUnidadMedida();
        ControladorConversion controladorConversion = new ControladorConversion();

        listaComprasProductos.add(nuevaCompra);
        this.listaComprasProductos.sort(Collections.reverseOrder());
        modelTable.setRowCount(0);
        actualizarLista();

        modelTable.fireTableDataChanged();
//        System.out.println(modelTable.getRowCount());
    }
 public void init() {
        this.table.setModel(modelTable);
      
//        tabbedPane.putClientProperty(FlatClientProperties.STYLE, ""
//                //                + "dropLineShortColor:$Menu.background;"
//                + "selectedBackground: $Login.background;"
//                + "hoverColor: $Login.background;"
//                //                + "tabSeparatorColor: $Menu.background;"
//                + "selectedForeground: $Table.foreground;"
//                + "foreground:$Table.foreground;"
//                + "background:$Login.background;"
//        );
        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25;"
                + "background:$background"
        );
        
        table.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "height:30;"
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                //                                + "dropLineShortColor:$Menu.background;"
                + "font:bold;"
                + "background:$Menu.background;"
        );
        
        table.putClientProperty(FlatClientProperties.STYLE, ""
                + "rowHeight:30;"
                + "showHorizontalLines:true;"
                + "showVerticalLines:true;"
                + "intercellSpacing:0,1;"
                //                + "dropLineShortColor:$Menu.background;"
                + "cellFocusColor:$TableHeader.hoverBackground;"
                + "selectionBackground:$TableHeader.hoverBackground;"
                + "selectionForeground:$Table.foreground;"
                + "background:$Login.background;"
        );    

        TableColumnModel columnModel = table.getColumnModel();
        TableColumn columnaCantidad = columnModel.getColumn(0);

        
        columnModel = table.getColumnModel();
        columnaCantidad = columnModel.getColumn(0);
        columnaCantidad.setPreferredWidth(10);
        
    }

}
