/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.panin.application.form.insumos;

import com.panin.application.form.productos.*;
import com.formdev.flatlaf.FlatClientProperties;
import com.panin.controladores.ControladorComprasInsumos;
import com.panin.controladores.ControladorInsumos;
import com.panin.dto.formAgregarInsumoProductoDTO;
import com.panin.entidades.ComprasInsumo;
import com.panin.entidades.Insumo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricke
 */
public class panelRegistrosInsumos extends javax.swing.JPanel {

    /**
     * Creates new form panelContenidoReceta
     */
    private List<ComprasInsumo> listaInsumos;
    private DefaultTableModel modelTable;

    public List<ComprasInsumo> getListaInsumos() {
        return listaInsumos;
    }

    public void setListaInsumos(List<ComprasInsumo> listaInsumos) {
        this.listaInsumos = listaInsumos;
    }

    public void agregarCompra(ComprasInsumo nuevaCompra) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String strDate = formatter.format(nuevaCompra.getFecha());
        System.out.println(strDate);
        SimpleDateFormat formatterh = new SimpleDateFormat("HH:mm:ss:");
        String strHora = formatter.format(nuevaCompra.getHora());
        System.out.println(strHora);

        modelTable.addRow(new Object[]{strDate, strHora, nuevaCompra.getCantidad().toString(), nuevaCompra.getUnidadMedidaId().getAbreviatura(), nuevaCompra.getPrecio().toString()});
        modelTable.fireTableDataChanged();
        System.out.println(modelTable.getRowCount());
    }

    public void iniciar(Insumo insumo) {

        ControladorComprasInsumos controladorComprasInsumos = new ControladorComprasInsumos();

        this.listaInsumos = controladorComprasInsumos.obtenerComprasdeUnInsumo(insumo);

        System.out.println(listaInsumos.size());
        for (ComprasInsumo ci : listaInsumos) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            String strDate = formatter.format(ci.getFecha());
            System.out.println(strDate);
            SimpleDateFormat formatterh = new SimpleDateFormat("HH:mm:ss:");
            String strHora = formatter.format(ci.getHora());
            System.out.println(strHora);

            modelTable.addRow(new Object[]{strDate, strHora, ci.getCantidad().toString(), ci.getUnidadMedidaId().getAbreviatura(), ci.getPrecio().toString()});
            modelTable.fireTableDataChanged();
            System.out.println(modelTable.getRowCount());
        }

    }

    public panelRegistrosInsumos() {
        String[] columnas = new String[]{
            "Fecha", "Hora", "Cantidad", "Unidad Medida", "Precio"
        };
        modelTable = new DefaultTableModel(columnas, 0);
        initComponents();
        init();

    }

    public panelRegistrosInsumos obtenerPanel() {
        return this;
    }

    public void init() {
        this.table.setModel(modelTable);
        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:25;"
                + "background:$background"
        );

        table.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "height:30;"
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                //                + "separatorColor:$TableHeader.background;"
                + "font:bold;"
        );

        table.putClientProperty(FlatClientProperties.STYLE, ""
                + "rowHeight:30;"
                + "showHorizontalLines:true;"
                + "intercellSpacing:0,1;"
                //                + "separatorColor:$TableHeader.background;"
                + "cellFocusColor:$TableHeader.hoverBackground;"
                + "selectionBackground:$TableHeader.hoverBackground;"
                + "selectionForeground:$Table.foreground;"
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        separador = new javax.swing.JSeparator();
        botonAbrirFrameFormularioInsumo = new javax.swing.JButton();

        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Cantidad", "Unidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        scroll.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        botonAbrirFrameFormularioInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/utilidad/agregar.png"))); // NOI18N
        botonAbrirFrameFormularioInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirFrameFormularioInsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(separador)
                .addGap(86, 86, 86))
            .addComponent(scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(botonAbrirFrameFormularioInsumo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(botonAbrirFrameFormularioInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbrirFrameFormularioInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirFrameFormularioInsumoActionPerformed
        // TODO add your handling code here:}
//        frameIngresarInsumoReceta frame = new frameIngresarInsumoReceta(this);
//        frame.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosed(WindowEvent e) {
//                String dato1 = frame.getName();
//                System.out.println(".windowClosed()");
//                System.out.println("Desde panel receta recibo " + frame.getDtoAgregarInsumo().getInsumo());
//                modelTable.addRow(new Object[]{frame.getDtoAgregarInsumo().getInsumo(), frame.getDtoAgregarInsumo().getUnidadMedidad(), frame.getDtoAgregarInsumo().getCantidad()});
//                
//                listaDTO.add(frame.getDtoAgregarInsumo());
//            }
//        });
    }//GEN-LAST:event_botonAbrirFrameFormularioInsumoActionPerformed

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirFrameFormularioInsumo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
